# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChatDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChatDemo
  pod 'Alamofire', '~> 5.2'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Toast-Swift', '~> 5.0.1'

#  target 'ChatDemoTests' do
#    inherit! :search_paths
#    # Pods for testing
#  end
#
#  target 'ChatDemoUITests' do
#    # Pods for testing
#  end

end
