package cn.kk20.chat.mapper;

import cn.kk20.chat.model.UserModel;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Jan 30 10:48:00 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Jan 30 10:48:00 CST 2019
     */
    int insert(UserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Jan 30 10:48:00 CST 2019
     */
    UserModel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Jan 30 10:48:00 CST 2019
     */
    List<UserModel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Jan 30 10:48:00 CST 2019
     */
    int updateByPrimaryKey(UserModel record);

    UserModel selectByPassword(@Param("name") String name, @Param("password") String password);

    UserModel selectByName(@Param("name") String name);

}